// AUTO-GENERATED by scripts/optimize-textures.mjs — do not edit by hand.
// Content-hashed KTX2 texture URLs. Regenerate with: npm run textures:optimize
export const TEXTURE_URLS = {
  'earth-diffuse-8k': '/textures/earth-diffuse-8k.bebdeaa3.ktx2',
  'earth-night-4k': '/textures/earth-night-4k.59bc8389.ktx2',
  'earth-bump-4k': '/textures/earth-bump-4k.615c1430.ktx2',
  'earth-specular-4k': '/textures/earth-specular-4k.cdca3f28.ktx2',
  'earth-clouds-4k': '/textures/earth-clouds-4k.7d062a64.ktx2',
} as const;

export type TextureName = keyof typeof TEXTURE_URLS;
